#!/usr/bin/env python3
"""
cmd12 steps 2+3: full-resolution (567-mutation) lineage tree, parallel to
export_db15.py's 315-mutation tree.json/chains.json. Reuses the exact same
carrier-group/ladderize/tree-build/chain-build logic (imported from
export_db15.py) so the two trees are built identically apart from source
data -- only the input newick + carrier matrix differ.

Source newick was generated by running the lab's standard
csv_newick_gil_ver3.py on csv/567_full_newick_input_native_order_501.csv --
the raw DB15_singlecell_complete_eem_heatmap_namseop.csv (567 mutations x
503 raw columns) with sample columns left in their NATIVE file order
(confirmed by the user: correctly curated for this 567-mutation file --
do NOT reorder to match the 315-tree's column order, which was curated
for that smaller marker set) and TWO columns dropped:
  - 15CFb2_2beon_C12: not part of the 502-sample cohort at all.
  - 15R85Fb2001B9: part of the cohort (L2 by the 315-marker lineage
    assignment) but was the one sample breaking a clean L1/L2 root split
    in the native-order 502-sample rebuild (landed in the L1 branch
    instead of L2) -- excluded by explicit user instruction after that
    was confirmed, not a default/automatic exclusion.
An earlier attempt reordered columns to match the 315-tree and produced a
tree whose root did NOT recover the clean L1/L2 split at all (5-way
polytomy, heavily mixed-lineage branches) -- confirmed broken by that
mismatched ordering, discarded in favor of native-order.
"""
import csv
import json
from collections import defaultdict

from ete3 import Tree

import sys
sys.path.insert(0, '/home/namseop/0_kidney/organogenesis_bulb/scripts')
from export_db15 import ladderize_tree, assign_node_ids, build_tree_json, build_chains_json

DB15_DIR = "/home/namseop/0_kidney/lineage_bulb/db15"
OUT_DIR = "/home/namseop/0_kidney/organogenesis_bulb/data/DB15"
FULL_NWK = f"{DB15_DIR}/567_tgeem_singlecell_lineage_full.nwk"
FULL_INPUT_CSV = f"{DB15_DIR}/csv/567_full_newick_input_native_order_501.csv"
KIDNEY_LONG_CSV = f"{DB15_DIR}/csv/db15_kidney_vaf_long_mapped_with_depth.csv"


def load_full_heatmap():
    with open(FULL_INPUT_CSV, newline='') as f:
        rows = list(csv.reader(f))
    header = rows[0]
    sample_ids = header[1:]
    mutation_ids = []
    matrix = []
    for row in rows[1:]:
        mutation_ids.append(row[0])
        matrix.append([float(v) for v in row[1:]])
    return mutation_ids, sample_ids, matrix


def build_carrier_groups(mutation_ids, sample_ids, matrix):
    groups = defaultdict(list)
    for mi, mutation_id in enumerate(mutation_ids):
        carriers = frozenset(sample_ids[si] for si, v in enumerate(matrix[mi]) if v > 0)
        groups[carriers].append(mutation_id)
    return groups


def main():
    tree = Tree(open(FULL_NWK).read().strip(), format=1)
    ladderize_tree(tree)

    mutation_ids, sample_ids, matrix = load_full_heatmap()
    carrier_groups = build_carrier_groups(mutation_ids, sample_ids, matrix)

    id_of = assign_node_ids(tree)
    tree_nodes, total_mut_assigned = build_tree_json(tree, id_of, carrier_groups)
    chains = build_chains_json(tree, id_of, tree_nodes)

    unassigned_mutation_ids = [m for m in mutation_ids if m not in total_mut_assigned]

    # panel membership: does this mutation have actual kidney target-seq VAF
    # data (i.e. is it one of the 315 confirmed panel mutations)? Ground
    # truth = mutation_ids actually present in the kidney long CSV, not "has
    # a PNG" -- one panel mutation is all-zero-VAF and has no PNG (skipped
    # at render time) but IS still real panel/sequencing data.
    panel_ids = set()
    with open(KIDNEY_LONG_CSV) as f:
        for row in csv.DictReader(f):
            panel_ids.add(row['mutation_id'])
    panel_mutation_ids = sorted(m for m in mutation_ids if m in panel_ids)
    non_panel_mutation_ids = sorted(m for m in mutation_ids if m not in panel_ids)

    with open(f"{OUT_DIR}/tree_full.json", 'w') as f:
        json.dump({
            "nodes": tree_nodes,
            "root_id": id_of[id(tree)],
            "unassigned_mutation_ids": unassigned_mutation_ids,
            "panel_mutation_ids": panel_mutation_ids,
        }, f)
    with open(f"{OUT_DIR}/chains_full.json", 'w') as f:
        json.dump({
            "chains": chains,
            "panel_mutation_ids": panel_mutation_ids,
        }, f)

    leaves = [n for n in tree_nodes.values() if n["is_leaf"]]
    print(f"node count: {len(tree_nodes)}")
    print(f"leaf count: {len(leaves)} (expect 502)")
    print(f"distinct mutation_ids assigned across all branches: {len(total_mut_assigned)} (of {len(mutation_ids)} total)")
    print(f"unassigned mutation_ids: {len(unassigned_mutation_ids)}")
    print(f"panel (315-confirmed, has kidney VAF data) mutation_ids present in this 567-set: {len(panel_mutation_ids)}")
    print(f"non-panel mutation_ids: {len(non_panel_mutation_ids)}")
    print(f"panel_mutation_ids + non_panel_mutation_ids = {len(panel_mutation_ids) + len(non_panel_mutation_ids)} (expect {len(mutation_ids)})")

    # exhaustive ladderize check
    def leaf_count(nid):
        n = tree_nodes[nid]
        if n["is_leaf"]:
            return 1
        return sum(leaf_count(c) for c in n["children"])

    bad = []
    for nid, n in tree_nodes.items():
        if n["is_leaf"]:
            continue
        counts = [leaf_count(c) for c in n["children"]]
        if not all(counts[i] >= counts[i + 1] for i in range(len(counts) - 1)):
            bad.append((nid, counts))
    n_internal = sum(1 for n in tree_nodes.values() if not n["is_leaf"])
    print(f"\nladderize check: {n_internal} internal nodes, {len(bad)} violating descending-leaf-count order")
    for b in bad[:5]:
        print("  VIOLATION:", b)

    root = id_of[id(tree)]

    def show(nid, depth=0, max_depth=3):
        n = tree_nodes[nid]
        if n["is_leaf"] or depth > max_depth:
            return
        counts = [leaf_count(c) for c in n["children"]]
        print("  " * depth + f"{nid} children leaf-counts: {counts}")
        for c in n["children"]:
            show(c, depth + 1, max_depth)

    print("\nladderize spot-check (near root):")
    show(root)

    # L1/L2 founder-split recovery check: the root (or its first
    # near-root branch point) should cleanly separate into ~252 L1-only
    # vs ~250 L2-only leaves, matching the known founder split from the
    # 315-tree -- not force it, just report what's actually there.
    lineage_of = {}
    with open(f"{DB15_DIR}/csv/DB15_singlecell_lineage_assignment.csv") as f:
        for row in csv.DictReader(f):
            lineage_of[row['sample']] = row['lineage']
    L1 = {s for s, l in lineage_of.items() if l == 'L1'}
    L2 = {s for s, l in lineage_of.items() if l == 'L2'}

    def leaves_of(nid):
        n = tree_nodes[nid]
        if n["is_leaf"]:
            return {n["leaf_name"]}
        s = set()
        for c in n["children"]:
            s |= leaves_of(c)
        return s

    print(f"\nL1/L2 founder-split check (known: L1={len(L1)}, L2={len(L2)}):")
    root_node = tree_nodes[root]
    check_node = root
    # if root is a single-child pass-through (common newick-wrapping
    # artifact), descend to the first node with >1 child before judging
    while len(tree_nodes[check_node]["children"]) == 1:
        check_node = tree_nodes[check_node]["children"][0]
    children = tree_nodes[check_node]["children"]
    print(f"  first branching node: {check_node}, {len(children)} children")
    for c in children:
        leaves = leaves_of(c)
        n_l1 = len(leaves & L1)
        n_l2 = len(leaves & L2)
        print(f"    {c}: total={len(leaves)} L1={n_l1} L2={n_l2}")
    clean_split = False
    if len(children) == 2:
        c0_l1, c0_l2 = len(leaves_of(children[0]) & L1), len(leaves_of(children[0]) & L2)
        c1_l1, c1_l2 = len(leaves_of(children[1]) & L1), len(leaves_of(children[1]) & L2)
        # each child must be 100% one lineage, 0% the other
        clean_split = (c0_l2 == 0 and c1_l1 == 0) or (c0_l1 == 0 and c1_l2 == 0)
    print(f"  CLEAN 2-way lineage-pure split (zero cross-contamination): {clean_split}")
    if not clean_split:
        for c in children:
            leaves = leaves_of(c)
            stray_l1 = leaves & L2 if len(leaves & L1) > len(leaves & L2) else set()
            stray_l2 = leaves & L1 if len(leaves & L2) > len(leaves & L1) else set()
            if stray_l1:
                print(f"    stray L2 sample(s) in mostly-L1 branch {c}: {sorted(stray_l1)}")
            if stray_l2:
                print(f"    stray L1 sample(s) in mostly-L2 branch {c}: {sorted(stray_l2)}")


if __name__ == '__main__':
    main()
